#! /bin/sh
sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor VGA-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           8
bspc config top_padding 	 35
bspc config right_padding 	 3
bspc config bottom_padding  	 3
bspc config left_padding  	 3

bspc config focused_border_color	"#ff5100"
bspc config normal_border_color		"#383838"

bspc config split_ratio          0.45
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a Tixati desktop='^10'
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#переключение раскадок клавиатуры
setxkbmap "us,ru" ",winkeys" 'grp:alt_shift_toggle'

#установка обоев
feh --bg-scale ~/Wall/wall2.jpg

#запуск полибара
bash ~/.config/polybar/launch.sh

#запуск композитора
picom

#запуск сервиса уведомлений
dunst
